### ISSUE TITLE
fix unordered lists not indenting/bulleting properly

### ISSUE THREAD

**Issue by nicsrlv** [the-engine-room/level-up#117]
<ul> bullets not listing properly on some pages - control for inconsistency and fix where needed

examples:

https://levelupcc.github.io/level-up/curriculum/safer-workspaces/tails/input/staying-anonymous-using-tails/

https://levelupcc.github.io/level-up/you-the-trainer/ice-breakers-and-energizers/

**Comment by joncamfield** [comment]
This appears to be working.  For markdown, list elements must follow either a header element or a blank line to "render" , so :

```
blahblah blah blah cyber cyber
* cyber
* cyber? 

```
won't render, but :

```
blahblah blah blah cyber cyber

* cyber
* cyber? 
```

will
