### ISSUE TITLE
move comment+feedback block to bottom of ADIDS-theme page layout

### ISSUE THREAD

**Issue by nicsrlv** [the-engine-room/level-up#124]
move comment + feedback block to bottom of page on module & theme pages (so module & element links are not all the way at bottom)

**Comment by joncamfield** [comment]
@nicsrlv  please review the changes at https://dev.level-up.cc/ for this; I removed the feedback block altogether and de-duplicated it with the footer content, also addressing #131

**Comment by joncamfield** [comment]
New "fat" footer style screenshot with links replacing hypothes.is box on content pages:

![image](https://user-images.githubusercontent.com/212852/64702977-8b9d8b80-d479-11e9-9270-dc9cb1590cd1.png)

old footer: 

![image](https://user-images.githubusercontent.com/212852/64703064-b4258580-d479-11e9-8143-a5adc3659c62.png)
