### ISSUE TITLE
update mailing list request link(s) with [listname-subscribe@lists.riseup.net]

### ISSUE THREAD

**Issue by nicsrlv** [the-engine-room/level-up#132]
Change from "request to join" CTA to separate request link with <mailto: levelup-subscribe@lists.riseup.net>

**Comment by mayarichman** [comment]
@nicsrlv I've updated the codebase, it just needs to be pulled into the server.

**Comment by joncamfield** [comment]
Merging @mfc 's commit to address this on the about page.  As per @mfc 's commit message, the contribute page also needs updating: "probably also need to update the contribute page: https://github.com/levelupcc/level-up/blob/gh-pages/_pages/community/contribute/contribute.md"

**Comment by mfc** [comment]
i added the content in latest merge request: https://github.com/levelupcc/level-up/pull/176
