### ISSUE TITLE
update installing Tails to point to Tails Installation Assistant

### ISSUE THREAD

**Issue by mfc** [the-engine-room/level-up#135]
The [Install Tails section](https://github.com/levelupcc/level-up/blob/gh-pages/_pages/curriculum/safer-workspaces/tails/deepening/installing-launching-replicating-tails/installing-launching-replicating-tails.md#step-2-installing-tails) should probably be replaced with a link to: https://tails.boum.org/install/ as the default first option, then the other instructions as backup offline instructions.

**Comment by mayarichman** [comment]
hey @mfc where in the text would you put the reference to the Tails install page?

**Comment by mfc** [comment]
created a pull request where it might be good.
