### ISSUE TITLE
Ensure https/LetsEncrypt process is working

### ISSUE THREAD

**Issue by joncamfield** [the-engine-room/level-up#146]
Ensure certbot is successfully updating without intervention

Check site update process to make sure site update is not clobbering valuable certbot validation files

**Comment by mfc** [comment]
currently deployed cert expired 2017-4-16, causing user warnings upon visiting website.

**Comment by joncamfield** [comment]
The site is now behind deflect.ca which is managing the LE process. Server->Deflect certs are provided by deflect and valid until 2029.
