### ISSUE TITLE
Google indexes old pages

### ISSUE THREAD

**Issue by blazman** [the-engine-room/level-up#147]
In lieu of a search feature on the site I tried to look up any content on veracrypt using a google search for 'site:level-up.cc veracrypt'. There isn't any so I changed it to 'truecrypt'. This brought back results but they both went to 404 pages like https://www.level-up.cc/leading-trainings/training-curriculum/encryption or from another search https://www.level-up.cc/printpdf/291

Can you force a re-index of the site?

**Comment by joncamfield** [comment]
This appears to have resolved itself, and may have partially been because the content was never replaced on the new site. I have opened a new issue to discuss that.
