### ISSUE TITLE
broken links / link mismatch between website and github

### ISSUE THREAD

**Issue by mfc** [the-engine-room/level-up#148]
In the [contribute section](https://level-up.cc/community/contribute/#how-can-i-contribute-content) "2. Submit Content as a Pull Request on GitHub", the links are:

* Using GitHub to Contribute Content: https://github.com/the-engine-room/wiki/How-to-Add-Content#adding-a-new-community-resource
* Using GitHub to Edit Existing Content: https://github.com/the-engine-room/wiki/How-to-Edit-Content
* Using GitHub to Add New Content Pages: https://github.com/the-engine-room/wiki/How-to-Add-Content#adding-a-new-page

which break / are not real links.

However in the github they are correctly `github.com/levelupcc/....` links:
https://github.com/levelupcc/level-up/blob/gh-pages/_pages/community/contribute/contribute.md#2-submit-content-as-a-pull-request-on-github

**Comment by joncamfield** [comment]
These have been fixed on dev by the most recent pull.
