### ISSUE TITLE
accept new content

### ISSUE THREAD

**Issue by mayarichman** [the-engine-room/level-up#160]
Hey @nicsrlv !

Thanks for all the new content from SMEX! There are a few steps that the revival team identifited that need to happen before the content goes live.

- [x] copy-edit new content, if needed @noegg @fabrider
- [x] rearrange content to fit IA, if needed @noegg @joncamfield @mayarichman
- [x] review dev deploy steps and test on dev @mayarichman @joncamfield 
- [x] pull to live directory @mayarichman @joncamfield 
- [x] migrate content to eclips server @houndbee

**Comment by mayarichman** [comment]
Link missing from section: Assessing Risk and Solutions / Security Plans and Protocols / I Decide [NEED RESOURCE FROM IWPR IN ORDER TO RESOLVE]

@nicsrlv

**Comment by mayarichman** [comment]
missing link/content in **rethinking security / digital security motivations / personal perceptions of security**

change title from rethinking security to defining and framing security

@nicsrlv

**Comment by mayarichman** [comment]
Add link to “Digital Security Decisions” in the paragraph:

 _This session builds on the work started during the Input session “Digital Security Decisions” in which participants began to reflect on and identify their needs. Now, you will work with participants to begin identifying specific tools and practices for themselves._ 

https://levelupcc.github.io/level-up/curriculum/assessing-risks-and-solutions/security-plans-and-protocols/activity-discussion/i-decide/

**Comment by mayarichman** [comment]
Double check that link below works on dev site 

_Copies of WHRD case infographics (download .pdf)_

https://levelupcc.github.io/level-up/curriculum/assessing-risks-and-solutions/security-plans-and-protocols/input/digital-security-decisions/

**Comment by mayarichman** [comment]
formatting / markdown issue in content below

_**Step 2 | ** Remaining in pairs, now ask participants to share with one another some of the barriers or challenges they anticipate facing within their organizations when presenting their security plans and articulating the need to begin an implementation process.
-- | --_


https://levelupcc.github.io/level-up/curriculum/assessing-risks-and-solutions/security-plans-and-protocols/input/digital-security-plans-and-protocols-post-training-replication/

**Comment by houndbee** [comment]
Hyperlink "Personal Perceptions of Security" in section **Step6** of page "Rethinking Security - Digital Security: Motivations, Resistances and Barriers
Your Rights, Your Technology"

**Comment by mayarichman** [comment]
Broken image - check on dev site

_Step 3 | Draw a table like the one below on a large piece of flipchart paper, and list out a number of digital risks under the “Digital Risk” column, using the different risks discussed and shared in Step 1 as examples (be sure to leave room on the right side to add additional columns for later parts of this session):_  


https://levelupcc.github.io/level-up/curriculum/assessing-risks-and-solutions/security-plans-and-protocols/deepening/gender-based-risk-model/

**Comment by joncamfield** [comment]
I think the image breaking is due to the github.io usage; it works on the dev site

**Comment by joncamfield** [comment]
See current dev testing steps at https://github.com/levelupcc/level-up/wiki/Server---Deploy-Management#test-and-deploy----on-the-linode-current----this-will-change-to-eclipsis-soon

**Comment by joncamfield** [comment]
> missing link/content in **rethinking security / digital security motivations / personal perceptions of security**
> 
> change title from rethinking security to defining and framing security
> 
> @nicsrlv

This was either done or I cannot figure out what further needs doing

**Comment by joncamfield** [comment]
Deployed to dev

**Comment by joncamfield** [comment]
Deployed to live!
