### ISSUE TITLE
Add to Contributor workflow documentation

### ISSUE THREAD

**Issue by mayarichman** [the-engine-room/level-up#161]
You can add to this documentation that will be give to whoever maintains the site:

https://docs.google.com/document/d/1n6w4ePEpO1b-80TF5_obT4v3XnG4VUcIdKOdjjmd7YA/edit

Possible Workflow:
 
Contributor forks levelupcc
Contributor adds new content
Contributor does pull request to levelupcc/dev
Maintainer reviews pull request and merges into dev
Git Webhook triggers Sintra app to build site and pushes to dev.level-up.cc directory on the eclips server
Maintainer reviews dev.level-up.cc and merges into gh-pages (live)
Git Webhook triggers Sintra app to build site and pushes to level-up.cc directory on the eclips server

**Comment by joncamfield** [comment]
FWIW this is very close to working, via travis instead of sintra, but following this same approach.

**Comment by joncamfield** [comment]
Closing this in lieu of the updated server workflow and the existing wiki and LU contribution docs https://github.com/levelupcc/level-up/wiki/How-to-Add-Content
