### ISSUE TITLE
Research transition to github actions 

### ISSUE THREAD

**Issue by joncamfield** [the-engine-room/level-up#185]
travis-ci is further limiting its free / floss tier, so we need to investigate if we can leverage gh actions to deploy via secrets to remote ssh servers to restore automation.

**Comment by joncamfield** [comment]
review https://zellwk.com/blog/github-actions-deploy/ and also  https://christianspecht.de/2020/05/03/building-and-deploying-a-jekyll-site-via-github-actions/

**Comment by tingeber** [comment]
We have a working solution for automated deployment through Github Actions: I  made a draft PR here https://github.com/levelupcc/level-up/pull/186

It should have all the info we need to finalize the transition to GH Actions
