### ISSUE TITLE
[news & updates] add new site launch and intro post

### ISSUE THREAD

**Issue by mayarichman** [the-engine-room/level-up#69]

**Comment by megdeb** [comment]
@nicsrlv  this could be a launch of the site announcement

**Comment by nicsrlv** [comment]
@megdeb yeah that makes most sense. i'll add it to my to-dos.

**Comment by nicsrlv** [comment]
- site launch post
- levelup story
- future of levelup

**Comment by nicsrlv** [comment]
@mayarichman could we test this out with the blog post you sent over to me for me to review?
