### ISSUE TITLE
request first round of feedback from community

### ISSUE THREAD

**Issue by megdeb** [the-engine-room/level-up#71]
a) bug fixes
b) content-specific changes and modifications
c) additional content requests (to be created by community)

**Comment by megdeb** [comment]
current bugs discovered are more related to back-end content pushes. i am playing around with the different things people might want to add to the site such as news, updates and other modules in order to make sure no errors are kicked back.

**Comment by nicsrlv** [comment]
Let's push this to post-launch.

**Comment by joncamfield** [comment]
May I suggest closing this issue based on the revived community engagement via list feedback and post-IFF2017 work?
