### ISSUE TITLE
added a new module to /curriculum/protecting-data, but am receiving a 404 error

### ISSUE THREAD

**Issue by megdeb** [the-engine-room/level-up#72]
@hedr don't know why this is happening ... but assuming its a landing page problem?

https://levelupcc.github.io/level-up/curriculum/protecting-data/creating-and-managing-strong-passwords/

**Comment by megdeb** [comment]
@hedr any news on this?

**Comment by megdeb** [comment]
@hedr  Looks like the original 404 error was fixed, but now i am getting the same error message for both the INPUT and the SYNTHESIS ... argh!

**Comment by ghost** [comment]
permalinks have to match the parent page. the permalink in synthesis doesn't match. just copy paste them into their respective pages to avoid typing errors. fixed the issue on my end:
![fixed_adids](https://cloud.githubusercontent.com/assets/11597596/16068328/b0b993fe-32f7-11e6-8904-1130b49f235e.png)

**Comment by ghost** [comment]
works on the site now. closing this
