### ISSUE TITLE
receiving page build error from github regarding the distribution of binary files

### ISSUE THREAD

**Issue by megdeb** [the-engine-room/level-up#73]
@hedr please see email i sent over tonight. this is happening every time i push something to github ... :(

**Comment by ghost** [comment]
Oh dont worry about it afaik its because of some packages in node modules
that github sorta interprets as like software releases or whatever so it
gives that message that i should distrubute/release them as such

**Comment by mayarichman** [comment]
@hedr  Should you .gitignore the node modules so they aren't added to the repo?

**Comment by ghost** [comment]
i did so it shouldn't be there anymore
