### ISSUE TITLE
fix dates across modules

### ISSUE THREAD

**Issue by megdeb** [the-engine-room/level-up#83]

**Comment by nicsrlv** [comment]
Question - does this refer to consistency with date metadata? Some are YYYY-DD-MM (with 00 for Day) and others are YYYY-MM, which makes more sense since we don't list the days typically.

**Comment by ghost** [comment]
this can easily be fixed dev-wise. let me know which format you want to
use.

here's a resource of data formats in jekyll:
http://alanwsmith.com/jekyll-liquid-date-formatting-examples

**Comment by nicsrlv** [comment]
@hedr thanks! YYYY-MM would be ideal (what we've traditionally used).

What's the best way for us to represent the date metadata in the .md files to make this easier?

**Comment by nicsrlv** [comment]
Note: changing dates from YYYY-DD-MM to YYYY-MM across the board.
